language: php

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=1

script: phpunit

sudo: false

notifications:
  email: false
