language: php

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=master WP_MULTISITE=0
  # - WP_VERSION=master WP_MULTISITE=1
  # - WP_VERSION=4.8 WP_MULTISITE=0
  # - WP_VERSION=4.8 WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

sudo: false

notifications:
  email: false
